### ISSUE TITLE
Feature request: Retain Iterator

### ISSUE THREAD

**Issue by Popog** [bluss/indexmap#11]
Have `retain` return a iterator over the extracted values, similar to `Drain` in the standard library, or my [PreRFC](https://internals.rust-lang.org/t/pre-rfc-retain-iterators-api-for-hashset-hashmap-vec-vecdeque/4164/4).

It seems like a relatively simple change, so if you're interested I could probably get it done and shoot you a PR later this week.

**Comment by bluss** [comment]
Since this is in the interest of demoing it for libstd, it makes sense. It's not good if we have an iterator that doesn't adhere to the element order of the map, though.

**Comment by bluss** [comment]
Removing the breaking label because retain() should stay as it is (compatible with HashMap), but we can add new methods.

**Comment by cuviper** [comment]
The current equivalent in `std` would be [`HashMap::drain_filter`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.drain_filter), but this hasn't been stabilized yet.

**Comment by cuviper** [comment]
We'll let #242 track `drain_filter`.
