### ISSUE TITLE
Consider converting README to markdown

### ISSUE THREAD

**Issue by jplatte** [bluss/indexmap#168]
I don't think crates.io understands RST, so it would be nice to convert the README to markdown for crates.io to be able to render it.

**Comment by cuviper** [comment]
I don't know if crates.io understands RST, but I think it won't even try unless `readme` is set in `Cargo.toml`, so right now it's just showing the `description`.

(I personally would prefer markdown too.)

**Comment by jplatte** [comment]
It doesn't seem like the `readme` field has to be set if the file is named exactly `README.md`:

* [const_unit_poc 1.1.1 on crates.io](https://crates.io/crates/const_unit_poc/1.1.1)
* [const_unit_poc 1.1.1's `Cargo.toml`](https://docs.rs/crate/const_unit_poc/1.1.1/source/Cargo.toml.orig)

**Comment by jplatte** [comment]
Also, looked it up; crates.io [does not support rST](https://github.com/rust-lang/crates.io/issues/1223).

**Comment by cuviper** [comment]
RST seems to be @bluss's preference across many projects, but I do think it would be nice to have the full README on crates.io.

**Comment by bluss** [comment]
reStructuredText is beautiful in plain text, but one drawback is that it is more reliant on editor support than markdown. Of course changing the format is ok, make sure to split out the release notes into a RELEASES.md or similar in that case.  For ndarray we use a separate "crates.io" readme file, which is another option.
