### ISSUE TITLE
function can make c.core = c.core.split_off(lo);  

### ISSUE THREAD

**Issue by gcxfd** [bluss/indexmap#172]
c.core = c.core.split_off(lo);  

use like below screenshot

![image](https://user-images.githubusercontent.com/69608605/108613595-81cdd500-742e-11eb-9088-deecc3db6dd7.png)

**Comment by cuviper** [comment]
The `core` field is a private implementation detail, but there is also a `split_off` method for `IndexMap` as a whole.

It appears you don't actually want two independent collections though. If you only want to keep the indexes `>= lo` and discard those `< lo`, you can call `c.drain(..lo)`.

**Comment by gcxfd** [comment]
thanks
