### ISSUE TITLE
docs.rs documentation isn't searchable

### ISSUE THREAD

**Issue by anahata0108** [bluss/indexmap#189]
I was reading the IndexMap docs and wanted to try to find some information on its support for serde. I tried searching like I do for other docs on docs.rs but typing in the box doesn't bring up the results like for other crates, and pressing enter to manually search doesn't produce any results. I checked my browser console and I see an error that https://docs.rs/crates-20210304-1.52.0-nightly-45b3c2851.js returns a 404. This isn't an issue with my browser / internet / configuration, as docs for other crates (e.g. serde) work properly.

**Comment by anahata0108** [comment]
I've done some more testing with this and it only seems to be broken on the docs index page. If I go to a page within the docs, searching works.

**Comment by bluss** [comment]
Thanks for the info. This must be a bug on the docs.rs end, but it's good to know.

**Comment by bluss** [comment]
fixed in current version
