### ISSUE TITLE
IndexMap doesn't implement `Debug`

### ISSUE THREAD

**Issue by Ethan1225** [bluss/indexmap#191]
I have: 
```
let mut test: IndexMap<&str, &str> = IndexMap::new();
test.insert("index1", "value1");
println!("{:?}", test);
```
test doesn't implement `Debug`

**Comment by cuviper** [comment]
There must be more to your problem, because this works fine in the playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6bcc805aa3a14b8bb6a2b689288bd829

**Comment by Ethan1225** [comment]
It can truly pass the compiler , but there is a warning prompt in the
jetbrains ide


Josh Stone ***@***.***>于2021年6月15日 周二23:29写道：

**Comment by cuviper** [comment]
If the IDE is inconsistent, you should ask JetBrains.

For instance, see also #148 and https://github.com/intellij-rust/intellij-rust/issues/4631.

**Comment by bluss** [comment]
Duplicates #148
