### ISSUE TITLE
Create indexmap/set in static contexts

### ISSUE THREAD

**Issue by mwillsey** [bluss/indexmap#202]
Would it be possible to add a `new`-like function that is `const`? It would be useful to create static maps without the aid of something like `once_cell`.

From scanning the code, it seems like `with_hasher` is maybe the right function to make `const`, since you don't have to make a hasher (it's given) and "no allocation" is already in the spec for that function.

**Comment by cuviper** [comment]
Since we now have const `Vec::new` and `RawTable::new` as well, yes I think this should be possible.

**Comment by mwillsey** [comment]
Happy to make a PR. Do you think `with_hasher` is the right target? Any others?

**Comment by cuviper** [comment]
A PR is welcome! I think `with_hasher` is the only constructor we can support. For precedent, the standard `HashMap` doesn't have any constant functions, but hashbrown does have constant `with_hasher` in its own map and set.

For other methods, `Vec` and/or `RawTable` don't give us anything else to work with, not even `len`.
