### ISSUE TITLE
Add Unstable Sort Methods

### ISSUE THREAD

**Issue by bhgomes** [bluss/indexmap#209]
It would be nice to have access to the unstable sorting algorithms:

- `IndexMap::sort_unstable_keys`
- `IndexMap::sort_unstable_by`
- `IndexMap::sorted_unstable_by`
- `IndexSet::sort_unstable`
- `IndexSet::sort_unstable_by`
- `IndexSet::sorted_unstable_by`

I can do a PR if there's interest.

**Comment by cuviper** [comment]
They should be `sort_unstable*` to remain similar to the slice methods, but otherwise that sounds fine.

**Comment by bhgomes** [comment]
Yes, you're right, I swapped them accidentally.
