### ISSUE TITLE
`pop_front`

### ISSUE THREAD

**Issue by ShadowJonathan** [bluss/indexmap#210]
I was surprised to not see this function in this library, but anyways;

I'm looking for a way to pop the first item of a map, it's alright if this disturbs the order, as long as i'm able to use `IndexMap` in both a lookup and queue fashion.

**Comment by cuviper** [comment]
In general, we look to `HashMap` for inspiration on unordered methods and `Vec` for ordered. The standard library only has `pop_front` for `LinkedList` and `VecDeque`, where the semantics are clear and the operation is cheap. The analogues from `Vec` would be `remove` and `swap_remove`, which you can certainly call with index 0. Here, we have called these `shift_remove_index` and `swap_remove_index`, and the latter will be faster if you don't mind disturbing the order.

**Comment by ShadowJonathan** [comment]
In that case i'll close this, thanks for the explaination.
