### ISSUE TITLE
Minimum Rust Version

### ISSUE THREAD

**Issue by mitsuhiko** [bluss/indexmap#214]
I am targeting 1.42 and up to yesterday's release it was actually possible to use this library with 1.42.0 despite being documented as targeting 1.49. I noticed that serde json now moved the minimum rust version for a specific feature to 1.46 (https://github.com/serde-rs/json/commit/aebe84cb09663d0c3371273fb20d838c2e752bcd) which apparently is now the lower bound.

As there has been some evidence for supporting rust versions below 1.49, would it make sense to actually lower the minimum rust version here in tests? I'm mostly asking because 1.49 is at least one version newer than what a lot of folks are currently using.

For some additional context here: `insta` depends on `serde-yaml` which in turn depends on `indexmap`. Because people are using `insta` for testing libraries that target versions lower than 1.49 this is now a small inconvenience.

**Comment by cuviper** [comment]
Our minimum comes from `hashbrown`. It might happen to work with older versions for now, but if they added anything that actually did require 1.49, we would have no ability to affect that here.

(Pinning older dependencies is possible, but I'd rather leave that to downstream users, so it doesn't hold *everyone* back.)

**Comment by mitsuhiko** [comment]
`hashbrown` according to their own readme moved up all the way to `1.51` at this point. For what it's worth I'm not entirely oppose to moving minimal versions up but considering that insta is a testing tool I'm generally trying to stay compatible with as much as possible since users depending on it don't like their testing tool determine the floor of what they can support.

**Comment by cuviper** [comment]
Hashbrown's bump hasn't been published yet. In the past, they've treated that as a semver change. For `indexmap`, since we're already 1.x, we've only used a minor version for MSRV increases.

**Comment by lnicola** [comment]
> Hashbrown's bump hasn't been published yet.

FWIW, it looks like `hashbrown` went all the way to 1.56.1: https://github.com/rust-lang/hashbrown/blob/HEAD/CHANGELOG.md#v0120---2022-01-17.

**Comment by luke-biel** [comment]
> For indexmap, since we're already 1.x, we've only used a minor version for MSRV increases.

Would you mind explaining why is that? I'm trying to wrap my head around the fact that one of my dependencies broke due to minor version upgrade through `insta`. I would consider MSRV bump something that requires MAJOR version bump.

**Comment by cuviper** [comment]
> I would consider MSRV bump something that requires MAJOR version bump.

This is not a universal opinion. For reference, Cargo documents the [change categories](https://doc.rust-lang.org/cargo/reference/semver.html#change-categories) including:
> - **Possibly-breaking change:** a change that some projects may consider major and others consider minor.

and then lists: [Possibly-breaking: changing the minimum version of Rust required](https://doc.rust-lang.org/cargo/reference/semver.html#env-new-rust)

By using a minor version bump for MSRV, we do at least leave the possibility of issuing new patch releases on older minors. But for the vast majority of Rust developers who stay close to the latest stable, we avoid the churn of a major version bump. That said, we do try to give a fair amount of time for that transition -- when we bumped to 1.49, that was already 6 months old.

**Comment by cuviper** [comment]
I don't see us changing policy here, and I just released indexmap 1.9.0 for hashbrown 0.12 and MSRV 1.56.1.

> Because people are using `insta` for testing libraries that target versions lower than 1.49 this is now a small inconvenience.

I do understand that inconvenience, as I do similar for other crates where I'm more conservative with MSRV. But I think it is necessary to allow the ecosystem move forward, and it's still _possible_ to test with older versions if you're careful with your lock file.
