### ISSUE TITLE
What is complexity of iteration over indexmap?

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [bluss/indexmap#227]
I recently [discovered](https://github.com/rust-lang/rust/pull/97215) that `std::collections::HashMap` iterator iterates over all items in map for _O(capacity)_, not _O(length)_.
Indexmap probably can have iteration for _O(length)_ using index based access. What is current complexity?

**Comment by cuviper** [comment]
The map iterators are based on the underlying vector of items, and that's contiguous, no deletion tombstones or anything like that. So yes, they should all be _O(length)_.

That's also true for the simple set iterators. The multi-set ones like `difference` or `union` do add hash lookups, but that's still _O(1)_ average, so I guess the same complexity overall.

**Comment by bluss** [comment]
This is basically described in the readme https://github.com/bluss/indexmap#performance  but the readme is old and needs updating, so sure, it's hard to know what to trust.

**Comment by AngelicosPhosphoros** [comment]
Well, it says that it is _performant_, it doesn't say exact complexity :)

**Comment by bluss** [comment]
Hm, it says the key-value pairs are stored in a Vec and the iteration is over them, densely, that's why it's basically describing it.
