### ISSUE TITLE
Rayon integration

### ISSUE THREAD

**Issue by bluss** [bluss/indexmap#25]
Ordermap's simple data structure again makes it easy to implement awesome stuff for?

**Comment by cuviper** [comment]
I have a prototype of Rayon support -- and yes, `Vec<Bucket>` makes this easy!
I'll try to post a PR soon...

**Comment by cuviper** [comment]
See #45 implementing the basic traits.

I think there's room to implement some useful extensions too, for almost anything involving iteration.
- `par_keys` and `par_values` could be simple maps on `ParIter`.
- `par_values_mut` could build on `ParIterMut`, but written directly it could do without `K: Sync`.
- `par_eq` could easily iterate and compare in parallel
- `retain` and `drain` might be possible in parallel, but Rayon doesn't do this for `Vec` either. (yet?)
- `MutableKeys` could add `iter_mut2` and `keys2`, and we could also provide parallel equivalents.

**Comment by bluss** [comment]
Fixed by #45 :tada:
