### ISSUE TITLE
`IndexMap` not supported with `serde_seq`

### ISSUE THREAD

**Issue by vriesk** [bluss/indexmap#252]
Would you accept a PR that adds `serde_seq_set` or similar to support `IndexSet`?

(could just use the same serialization as `IndexMap<T, ()>` behind the scenes to make this seamless)

**Comment by cuviper** [comment]
Sets are already serialized as a plain sequence.

**Comment by cuviper** [comment]
Closing, but feel free to reopen if I misunderstood you...
