### ISSUE TITLE
`binary_search` and `partition_point` on `Slice`

### ISSUE THREAD

**Issue by Eh2406** [bluss/indexmap#281]
Would it be possible to add `binary_search` and `partition_point` and friends on `Slice`?

Particular use case I have is an optimization of `retain`. I currently have `index_map.retain(|_, v| foo(&*v) < bar)` which works correctly. I happen to know that this `index_map` is sorted by `foo(&*v)`. I think it would be more efficient to do `let cut = index_map.partition_point(foo(&*v) < bar); index_map.truncate(cut)` (adjusted for off by one errors). But did not see the tools to do so.

**Comment by cuviper** [comment]
I think those methods should be fine on `IndexMap` and `IndexSet` as well as their respective `Slice`s.

This could also be a building block for `insert_sorted` per #89.

Are you interested in implementing this? I think it should be straightforward to wrap the normal slice methods.

**Comment by Eh2406** [comment]
I can give it a little time, happy to give it a try. Any pointers for to get started? Any gotchas to watch out for?

**Comment by cuviper** [comment]
I don't think there's anything weird -- e.g. here's one for `Slice<K, V>`:

```rust
    pub fn binary_search_by<'a, F>(&'a self, mut f: F) -> Result<usize, usize>
    where
        F: FnMut(&'a K, &'a V) -> Ordering,
    {
        self.entries.binary_search_by(move |p| f(&p.key, &p.value))
    }
```

**Comment by Eh2406** [comment]
I started by implement in them on `map` and `set` using `with_entries` inspired by the implementation of [`sort_by_cached_key`](https://github.com/bluss/indexmap/commit/8b7f398b2218c6da431d4cecf69ffe91ff066deb#diff-110e61eb735b79c762510f02f157a12094bcf2b9a15d2ed767532a0e3d5f7bafR747), which did not go well. Implementing them on slices went very smoothly, then the `map`/`set` can defer to `self.as_slice().foobar`.

Do you want the full documentation copied from std?

What level of testing seems appropriate?
