### ISSUE TITLE
Implement (behind a feature branch) the Merge Crate

### ISSUE THREAD

**Issue by RuboGubo** [bluss/indexmap#286]
I need this [crate](https://docs.rs/merge/0.1.0/merge/) derive for my project, and thought I would quickly drop by to write the issue and try to implement it. I don't see any reason why you would not do this, as it can all be hidden behind a feature flag for the people that don't need it.

**Comment by cuviper** [comment]
What would you want implemented here? There's no universal merge strategy to choose, so you will need to apply your own choice that makes sense in your own domain. At a glance, I don't think `indexmap` needs to do anything for that.

**Comment by RuboGubo** [comment]
I have made by best attempt at implementing it, feel free to tell me what you think, I think what I settled on makes sense though.

**Comment by cuviper** [comment]
> I think what I settled on makes sense though.

My point is that the `merge` crate doesn't even try to decide that for any standard library containers. They could have implemented for `Vec` or `HashMap`, either of which would have been useful precedent here, but instead their *absence* is precedent that there's no one right answer for a container.

**Comment by cuviper** [comment]
Let's leave it up to each user how they should be merged.
