### ISSUE TITLE
Signature of OccupiedEntry::insert

### ISSUE THREAD

**Issue by dtolnay** [bluss/indexmap#68]
- [OccupiedEntry::insert for HashMap](https://doc.rust-lang.org/std/collections/hash_map/struct.OccupiedEntry.html#method.insert)
- [OccupiedEntry::insert for BTreeMap](https://doc.rust-lang.org/std/collections/btree_map/struct.OccupiedEntry.html#method.insert)
- [OccupiedEntry::insert for LInkedHashMap](https://docs.rs/linked-hash-map/0.5/linked_hash_map/struct.OccupiedEntry.html#method.insert)
- [OccupiedEntry::insert for IndexMap](https://docs.rs/indexmap/0.4/indexmap/map/struct.OccupiedEntry.html#method.insert)

The first three all take `&mut self` while indexmap takes `self` by value. Is this intentional? I found this makes it complicated for a library to multiplex across different choices of underlying map type: https://github.com/serde-rs/json/issues/418.

My workaround is:

```rust
mem::replace(occupied_entry.get_mut(), value)
```

**Comment by cuviper** [comment]
Seems like something we should fix. Most of the API tries to be consistent with `HashMap`, and I don't see a reason why this would need an exception.

**Comment by bluss** [comment]
@dtolnay thanks a lot for catching this before our 1.0
