### ISSUE TITLE
push README+description update on ordermap to link to indexmap

### ISSUE THREAD

**Issue by vitiral** [bluss/indexmap#73]
The `description` in Cargo.toml should mention that it was renamed as well as README to prevent people from accidentally using it.

Thanks!

**Comment by cuviper** [comment]
Ah, you're right -- the 0.4.1 release note does mention deprecation, but we could make this more obvious, and also add the maintenance-deprecated badge.  Would you like to send a PR to the ordermap-0.4 branch?

**Comment by bluss** [comment]
Should be fixed now, https://crates.io/crates/ordermap
