### ISSUE TITLE
Implement Hash on IndexMap and IndexSet

### ISSUE THREAD

**Issue by lucab** [bluss/indexmap#75]
I'm currently looking into embedding an `IndexMap` into a larger recursive enum (which looks pretty similar to [this](http://arcnmx.github.io/serde-value/serde_value/enum.Value.html)). However I hit a blocker on my journey, as the type-checker complains that `IndexMap` does not implement `Hash` (duh).

While I think in theory it is quite unlikely to have a usecase where an `IndexMap` is used as an hashable key, the type system is technically correct on this. Would a PR to derive `Hash` on all the relevant types up to `IndexMap`+`IndexSet` be welcome here? For reference, within stdlib `BTreeMap` implements it but `HashMap` doesn't.

**Comment by cuviper** [comment]
See the closed #67 -- the main challenge is that `Hash` needs to be consistent with `Eq`.

**Comment by bluss** [comment]
I'm going to close this as there is no use case proposed for hashing the indexmap nor an algorithm that it should use. If I read the original report correctly, the map is embedded into a bigger type and it's entirely possible for you to define a domain specific hash and equality for that specific case.

**Comment by lucab** [comment]
@bluss glad that you are back! As an afterthought related to this, I was wondering if `PartialEq` should behave like the [BTreeSet one](https://doc.rust-lang.org/src/alloc/collections/btree/map.rs.html#1761-1765) instead, by taking item-order into account too?

**Comment by cuviper** [comment]
You can also use `Iterator::eq` to compare in order.

**Comment by lucab** [comment]
Sure, but I am talking about the commonly-used comparison, which is a potential hazard for anybody actually relying on insertion order for semantics.
As a quite common usecase for an example, let's take "de-duplicated ordered policy rules":

```rust
extern crate indexmap; // 1.0.2

// Policy: subject - verb - object
type Policies = indexmap::IndexSet<(&'static str, &'static str, &'static str)>;

fn main() {
    let mut rules1 = Policies::new();
    rules1.insert(("user", "allow", "ssh"));
    rules1.insert(("user", "deny", "ssh"));

    let mut rules2 = Policies::new();
    rules2.insert(("user", "deny", "ssh"));
    rules2.insert(("user", "allow", "ssh"));

    // This does not panic right now.
    assert_eq!(rules1, rules2)
}

```
