### ISSUE TITLE
Feature Request: `iter_full` and `iter_full_mut`

### ISSUE THREAD

**Issue by phayes** [bluss/indexmap#82]
I've recently run into a situation where I needed access to the key, mutable value, and position all at the same time.  I found myself fighting the borrow-checker trying to put something together with some combination `iter`, `iter_mut`, `get_full` and `get_full_mut`, and in the end I had to give up and manually track positions outside of the iter loop. 

Given all that, it would be super handy to have `iter_full` and `iter_full_mut` that would return a triplet of (key, value, position).

**Comment by cuviper** [comment]
Can't you just `enumerate()` it?

**Comment by phayes** [comment]
Aha!    That's likely the thing to do.   Closing this ticket.
