### ISSUE TITLE
Implement `serde` traits under `#[cfg(features = "serde")]`

### ISSUE THREAD

**Issue by zakarumych** [bluss/indexmap#84]
Instead of `#[cfg(features = "serde-1")]` which is bit counter-intuitive and not in consistency with rust ecosystem.

**Comment by garro95** [comment]
This would also be consistent with the Rust API Guidelines

**Comment by bluss** [comment]
With dependency renames available in cargo, this should be safe to do now

**Comment by clarfon** [comment]
Would it be possible to output a static error whenever `feature = "serde"` is enabled but `feature = "serde-1"` is not, at least until this change can be made? Found myself debugging this and was a bit confused why code wasn't working. :(

**Comment by cuviper** [comment]
An error is possible, but I think we should make the change to enable it all with just "serde". Then "serde-1" will be a vestigial feature that still enables the real "serde".
