### ISSUE TITLE
Implement serde::IntoDeserializer for IndexMap/IndexSet

### ISSUE THREAD

**Issue by Mingun** [bluss/indexmap#86]
It must be trivial because serde already has generic [`MapDeserializer`]: https://docs.serde.rs/src/serde/de/value.rs.html#1254-1266

[`MapDeserializer`]: https://docs.serde.rs/serde/de/value/struct.MapDeserializer.html

**Comment by cuviper** [comment]
When would one actually use `IntoDeserializer`? This is the first I've heard of it.

**Comment by Mingun** [comment]
For example, at implementation of a new format and structure, the containing IndexMap and similar [`serde_json::Value`] -- i.e. the type describing all possible values of the format. For example, I [implemented] [such type] in the my [`serde-gff`] library and can use it with [`serde-transcode`] in the idiomatic way:
```rust
extern crate serde;
extern crate serde_json;
extern crate serde_gff;
extern crate serde_transcode;

use serde::Serialize;
use std::io::{Write, BufWriter};
use std::fs::File;

fn main() {
    let value: serde_gff::Value = ...;
    let writer = BufWriter::new(File::create("output.json").unwrap());

    let mut serializer = serde_json::Serializer::pretty(writer);
    serde_transcode::transcode(&mut value.into_deserializer(), &mut serializer).unwrap();
    serializer.into_inner().flush().unwrap();
}
```

But you not the first who for the first time hears about `IntoDeserializer` :). This piece really, is not really clear documented.

[`serde_json::Value`]: https://docs.serde.rs/serde_json/enum.Value.html
[implemented]: https://github.com/Mingun/serde-gff/blob/master/src/de/value.rs#L317-L367
[such type]: https://github.com/Mingun/serde-gff/blob/master/src/value.rs#L159-L232
[`serde-gff`]: https://github.com/Mingun/serde-gff
[`serde-transcode`]: https://docs.rs/serde-transcode
