### ISSUE TITLE
Question about ordered remove

### ISSUE THREAD

**Issue by tspiteri** [bluss/indexmap#90]
I wanted to remove an element without perturbing the order of the remaining elements, and used something like the code below. Is there a better way than this? (In my case it is not really that important, this works just fine for me.)

```rust
type Map = IndexMap<K, V>;
fn remove_ordered(m: &mut Map, key: &K) -> Option<V> {
    let (index, _key, val) = m.swap_remove_full(key)?;
    if index < m.len() {
        let tail = m.len() - index - 1;
        let mut stack = Vec::with_capacity(tail);
        for _ in 0..tail {
            stack.push(m.pop().expect("disappearing elements"));
        }
        let (last_key, last_val) = m.pop().expect("disappearing elements");
        m.extend(stack.into_iter().rev());
        m.insert(last_key, last_val);
    }
    Some(val)
}
```

**Comment by dbeckwith** [comment]
Having an order-preserving remove is all that's stopping me from using this crate right now, would be perfect if that gets added!

**Comment by bcashier** [comment]
@cuviper Hi,

Do order-preserving remove feature already added or not yet please ?

If not, is there any faster alternative function to preserve the orders ?
