### ISSUE TITLE
1.0.3 release?

### ISSUE THREAD

**Issue by mwillsey** [bluss/indexmap#96]
What is needed to cut a 1.0.3 release?

I need the clonable iterators feature introduced in https://github.com/bluss/indexmap/commit/d8e5225a6183886045ded56cc278139ce87d1f17, as it provides parity with HashMap. I'd prefer to not depend on a git revision if possible. 

Is there some way I could help out on preparing a release?

(awesome create btw. I just sped up an application by > 30% by just switching to indexmap!)

**Comment by bluss** [comment]
Next version will be 1.1.0, and I could make the release when I have time. Biggest thing would be to update dev deps and other Rust version related things before the release

**Comment by mwillsey** [comment]
I'd be happy upgrade (dev) dependencies if you give me some constraints.
- Do you want to stay with Rust 1.18? Or move to some new msrv?
- Should I update all deps or just dev deps?

**Comment by bluss** [comment]
We'll need to move to a new minimum version, but hopefully it can be a bit conservative (so not latest stable). We'd aim to update all dependencies. You could start from https://github.com/bluss/indexmap/pull/85 and use cuviper's suggestion there too (to the extent possible).

The versioning policy is as given in the docs, we'll update the minimum rust version in 1.x minor versions, but be careful about it.
It's a fact of the ecosystem and Rust itself that we must gradually update the msrv.

**Comment by bluss** [comment]
Also awesome that indexmap was a speed up. It's a very useful datastructure. With the hashmap improvements in std (hashbrown was brought in as the new HashMap implementation), std is doing really well when it comes to performance. Indexmap could still have a leg up in a few situations, for example much faster iteration.

**Comment by mwillsey** [comment]
So the following will keep you at 1.30 for `cargo test`. Non-dev builds remain unaffected.

```diff
-itertools = "0.7.0" # 0.8 not compiles on Rust 1.18
-rand = "0.4"
-quickcheck = { version = "0.6", default-features = false }
+itertools = "0.8"
+rand = "0.6"
+quickcheck = { version = "0.8", default-features = false }
 fnv = "1.0"
-lazy_static = "1"
-serde_test = "1.0.5"
+lazy_static = "1.3"
+serde_test = "1.0.99"
```

`quickcheck` requires 1.30, and it's also what's stopping you from fully updating `rand` (it wants 0.6).

**Comment by cuviper** [comment]
FWIW, I'm revisiting #45 -- maybe we can finally get that done for a new release too.
